### ISSUE TITLE
Changing theme

### ISSUE THREAD

**Issue by j4m355** [YagoLopez/material-light#1]
Hi @YagoLopez - is there any easy way to change the colour theme with material-light?  I'm not spotting it, but could be missing the obvious.

Thank you

**Comment by YagoLopez** [comment]
Hi @j4m355 At this moment there is no option for changing themes globally. You can override element sytles individually, for example header-bars colors. In certain way is more flexible but I contamplate that posibility for the future and have CSS files with different themes ready. If you are interested I could send it to you to make a pull request.

I am in the process of documenting the api but my time is finite :) anyway thank you for your interest and hope to incoporate this feature soon in next releases.

Cheers.

**Comment by YagoLopez** [comment]
Here you have a couple of examples:

- If you want to change the `<ml-header>` background color, go to the component where it is (`app.layout.ts` in the demo) and put this in the template for example:

```
<style>
  ml-header {background: red;}
</style>
```
Now your `<ml-header>` will have background: red

- If you want to change the `<ml-button>` background color, do the same: go to the component where it is used (`pagButton.ts` in the demo) and put in the template:

```
<style>
  ml-button {background: yellow !important;}
</style>
```

All your buttons will have this background. You can use css selectors to choose what elements you target exactly.

- At this moment If you want styles applied globally you could add this to your index.html

```
<style>
  ml-header {background: red;}
  ml-button {background: yellow !important;}
</style>
```
And you would have to specify this metadata `@Component.encapsulation: ViewEncapsulation.None` in your components losing CSS encapsulation. It is a tradeoff until other solution be implemented.

I excluded themes initially for smaller files sizes and faster load times.

**Comment by j4m355** [comment]
Super. Thanks for taking the time to respond @YagoLopez - most appreciated. Looks good.

**Comment by YagoLopez** [comment]
A couple of questions more:

Using `/deep/` you can apply styles inside the component without breaking css encapsulation. In this case you dont need to use `@Component({encapsulation: ViewEncapsulation.None})`.

There is another special selector I'll use in the future to add themes and you can try if you want: `:host-context()`.

Here is the link to the official documentation about special selectors.
https://angular.io/docs/ts/latest/guide/component-styles.html

Hope that helps.
Cheers.
