### ISSUE TITLE
small-screen-only misspelled 

### ISSUE THREAD

**Issue by lorinpa** [YagoLopez/material-light#2]
Hi,
There is a typo in the following listing:
src/app/ml/components/layout/mlLayout.ts  

please change line 100 from:
host: {class: 'mdl-layout--small-screen-ongly'}})

to
host: {class: 'mdl-layout--small-screen-only'}})

In other words, "only" is misspelled.

**Comment by YagoLopez** [comment]
@lorinpa Thank you very much. It is fixed now.

Hope it wount cause you much trouble.

If you have any other issue any questions are welcome
